# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

wrapper <- function(xs, target, nn, m, cor) {
    .Call('SMOTE_wrapper', PACKAGE = 'SMOTE', xs, target, nn, m, cor)
}

