// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// wrapper
Rcpp::NumericVector wrapper(SEXP xs, SEXP target, SEXP nn, SEXP m, SEXP cor);
RcppExport SEXP SMOTE_wrapper(SEXP xsSEXP, SEXP targetSEXP, SEXP nnSEXP, SEXP mSEXP, SEXP corSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< SEXP >::type xs(xsSEXP );
        Rcpp::traits::input_parameter< SEXP >::type target(targetSEXP );
        Rcpp::traits::input_parameter< SEXP >::type nn(nnSEXP );
        Rcpp::traits::input_parameter< SEXP >::type m(mSEXP );
        Rcpp::traits::input_parameter< SEXP >::type cor(corSEXP );
        Rcpp::NumericVector __result = wrapper(xs, target, nn, m, cor);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
